engines:
  rubocop:
    enabled: true
    issue_override:
      severity: major
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
    issue_override:
      severity: info
ratings:
  paths:
    - "app/**/*"
    - Gemfile.lock
exclude_paths:
  - "app/foo.rb"
  - "**.ru"
  - "vendor/**"
